#!/bin/sh

for FILE in $(git diff --cached --name-only --diff-filter=ACMRTUX -- '*.c' '*.h')
do
        /usr/local/opt/llvm/bin/clang-format -i $FILE
        /usr/local/opt/llvm/bin/clang-tidy $FILE
done
